
package com.sforce.soap.authentication;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AuthenticationPortType", targetNamespace = "urn:authentication.soap.sforce.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthenticationPortType {


    /**
     * Are the supplied saleforce.com userId and password valid ?
     * 
     * @param parameters
     * @return
     *     returns com.sforce.soap.authentication.AuthenticateResult
     */
    @WebMethod(operationName = "Authenticate")
    @WebResult(name = "AuthenticateResult", targetNamespace = "urn:authentication.soap.sforce.com", partName = "parameters")
    public AuthenticateResult authenticate(
        @WebParam(name = "Authenticate", targetNamespace = "urn:authentication.soap.sforce.com", partName = "parameters")
        Authenticate parameters);

}
