
package com.sforce.soap.authentication;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * Sforce Authentication Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SforceAuthenticationService", targetNamespace = "urn:authentication.soap.sforce.com", wsdlLocation = "file:/D:/Harpreet/D/Astadia/dev/GAE/CodeLabExercise/CodeLabEx5Server-starter/war/AuthenticationService.wsdl")
public class SforceAuthenticationService
    extends Service
{

    private final static URL SFORCEAUTHENTICATIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.sforce.soap.authentication.SforceAuthenticationService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.sforce.soap.authentication.SforceAuthenticationService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/Harpreet/D/Astadia/dev/GAE/CodeLabExercise/CodeLabEx5Server-starter/war/AuthenticationService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/Harpreet/D/Astadia/dev/GAE/CodeLabExercise/CodeLabEx5Server-starter/war/AuthenticationService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SFORCEAUTHENTICATIONSERVICE_WSDL_LOCATION = url;
    }

    public SforceAuthenticationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SforceAuthenticationService() {
        super(SFORCEAUTHENTICATIONSERVICE_WSDL_LOCATION, new QName("urn:authentication.soap.sforce.com", "SforceAuthenticationService"));
    }

    /**
     * 
     * @return
     *     returns AuthenticationPortType
     */
    @WebEndpoint(name = "AuthenticationService")
    public AuthenticationPortType getAuthenticationService() {
        return super.getPort(new QName("urn:authentication.soap.sforce.com", "AuthenticationService"), AuthenticationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthenticationPortType
     */
    @WebEndpoint(name = "AuthenticationService")
    public AuthenticationPortType getAuthenticationService(WebServiceFeature... features) {
        return super.getPort(new QName("urn:authentication.soap.sforce.com", "AuthenticationService"), AuthenticationPortType.class, features);
    }

}
